name: Auto Build, Tag, and Release

on:
  push:
    branches:
      - main

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B package

      - name: Create tag and GitHub release
        run: |
            VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            NAME=$(mvn help:evaluate -Dexpression=project.name -q -DforceStdout)
            JAR=target/${NAME}-${VERSION}.jar
            
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git tag "$VERSION"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} "$VERSION"
            gh release create "$VERSION" "$JAR" --generate-notes --title "Release $VERSION" --fail-on-no-commits