name: Auto Tag, Build, and Release

on:
  push:
    branches:
      - main

jobs:
  all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        env:
          VERSION: $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          NAME: $(mvn help:evaluate -Dexpression=project.name -q -DforceStdout)

      - name: Create Tag
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git tag -a "${{ VERSION }}" -m "Release ${{ VERSION }}"
            git push origin "${{ VERSION }}"

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B package

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/${{ NAME }}-${{ VERSION }}.jar"
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          makeLatest: true
          tag: "${{ VERSION }}"